apiVersion: v1
kind: Pod
metadata: 
  name: loopr-pod1
  namespace: gitlab-agent-agent2
  labels:
    app: web
spec:
   containers: 
     name: nginnnx-v1
     image: nginx:latest
     ports:
      containerPort: 80
